name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang cmake curl zip unzip tar pkg-config autoconf autoconf-archive automake libtool libltdl-dev

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgGitCommitId: 4b77da7fed37817f124936239197833469f1b9a8

    - name: Configure CMake
      run: |
        export CC=clang
        export CXX=clang++
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --config Release
